name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pynwb
      run: |
        pip install git+https://github.com/NeurodataWithoutBorders/pynwb.git@cd3c352087a159dfab635c0cde4239fbede0973a
        pip install jsonschema
    - name: get namespace schema and validate
      run: |
        git clone https://github.com/ben-dichter-consulting/hdmf-common-schema.git
        cd hdmf-common-schema/
        git checkout -b 5b4c997d4b8dbf04a7237b46823e426efb165f74
        cd ..
        ls
        ls hdmf-common-schema
        python -m pynwb.testing.validate_spec core/nwb.namespace.yaml -m hdmf-common-schema/hdmf-language.namespace.schema.json
    - name: Validate schema specification
      run: |
        python -m pynwb.testing.validate_spec core -m nwb.schema.json
        
